version: '3.9'

services:
  ifstgbot:
    image: ifstgbot:latest
    build:
      context: ./app
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      MONGO_URL: "mongodb://mongodb:27017/firstsaturdaybot"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:5.0
    volumes:
      - "./data/mongodb:/data/db"