version: '3.9'

services:
  ifstgbot:
    image: ifstgbot:${TAG}
    profiles: ["build"]
    build:
      context: ./app
      dockerfile: ./Dockerfile
      target: build
    env_file:
      - .env
    environment:
      MONGO_URL: "mongodb://mongodb:27017/firstsaturdaybot"
    depends_on:
      - mongodb
  ifstgbot-tests:
    image: ifstgbot-tests:${TAG}
    profiles: ["tests"]
    build:
      context: ./app
      dockerfile: ./Dockerfile
      target: tests
  mongodb:
    image: mongo:5.0
    profiles: ["build"]
    volumes:
      - "./data/mongodb:/data/db"