from telegram.ext import ConversationHandler

(
    CURRENT_FEATURE,
    INCORRECT_INPUT,
    START_OVER,
    STOP_CONVERSATION,
    TO_START
) = map(chr,range(0,5))

(
    SET_NICKNAME,
    REMOVE_NICKNAME,
    TYPING_REPLY,
    SEND_PHOTO
) = map(chr,range(10, 14))

(
    SELECTING_ADMIN_ACTION,
    START_EVENT_TIME,
    END_EVENT_TIME,
    ADD_ADMIN,
    REMOVE_ADMIN,
    SET_STATISTIC_FORM_LINK,
    SET_PORTAL_HUNT_SPREADSHEET_LINK,
    TYPING_TIME_CONFIGURATION,
    TYPING_STATISTIC_SPREADSHEET_LINK,
    TYPING_PORTAL_HUNT_SPREADSHEET_LINK,
    TYPING_ADD_ADMIN,
    TYPING_REMOVE_ADMIN,
    SHOW_CURRENT_CONFIGURATION
)= map(chr,range(20, 33))

END = ConversationHandler.END