from telegram.ext import ConversationHandler

(
    CURRENT_FEATURE,
    INCORRECT_INPUT,
    START_OVER,
    STOP_CONVERSATION,
    TO_START
) = map(str, range(100, 105))

(
    SELECTING_USER_ACTION,
    SET_NICKNAME,
    SET_LANGUAGE,
    SHOW_PRIVACY_POLICY,
    REMOVE_NICKNAME,
    TYPING_NICKNAME,
    SEND_PHOTO
) = map(str, range(110, 117))

(
    SELECTING_ADMIN_ACTION,
    SET_START_EVENT_TIME,
    SET_END_EVENT_TIME,
    ADD_ADMIN,
    REMOVE_ADMIN,
    SET_STATISTIC_FORM_LINK,
    SET_PORTAL_HUNT_SPREADSHEET_LINK,
    SET_EVENT_RESTRICTION_POLICY,
    CHANGE_DATE_RESTRICTION,
    CHANGE_TIME_RESTRICTION,
    TYPING_TIME_CONFIGURATION,
    TYPING_STATISTIC_SPREADSHEET_LINK,
    TYPING_PORTAL_HUNT_SPREADSHEET_LINK,
    TYPING_ADD_ADMIN,
    TYPING_REMOVE_ADMIN,
    TYPING_EVENT_RESTRICTION,
    SHOW_CURRENT_CONFIGURATION
) = map(str, range(120, 137))

END: int = ConversationHandler.END
